@baseUrl=http://localhost:8080/actors
@id={{create.response.body.id}}

# @name getAll
GET {{baseUrl}}

###

# @name create
POST {{baseUrl}}
Content-Type: application/json

{
  "name": "Robert-{{$guid}}",
  "bio": "*** Bio description goes here ***",
  "bornAt": "1943-08-17",
  "movies": [
    { "movie_id": 4, "character_name": "Travis Bickle" }
  ]
}
###

# @name getOne
GET {{baseUrl}}/{{id}}

###

# @name update
PUT {{baseUrl}}/{{id}}

{
  "name": "Robert De Niro",
  "bio": "*** Bio description CHANGED goes here ***",
  "bornAt": "1943-08-17",
  "movies": [
    { "movie_id": 4, "character_name": "Travis Bickle" },
    { "movie_id": 3, "character_name": "A madeup character" }
  ]
}
###

# @name remove
DELETE {{baseUrl}}/{{id}}

###

# @name getMovies
# MG-0004 View Actor's movie appearances
GET {{baseUrl}}/{{id}}/movies

###

# @name getNrMoviesByGenre
# MG-0005 View Actor's number of Movies in Genres
GET {{baseUrl}}/{{id}}/genres/nr-movies

###

# @name getListOfCharacterNames
# MG-0006. View Actor's character names
GET {{baseUrl}}/{{id}}/character-names

###