@baseUrl=http://localhost:8080/genres
@id={{create.response.body.id}}

# @name getAll
GET {{baseUrl}}

###

# @name create
POST {{baseUrl}}
Content-Type: application/json

{
  "name": "jose-{{$guid}}"
}
###

# @name create
POST {{baseUrl}}
Content-Type: application/json

{
  "name": "jose2-{{$guid}}",
  "movies": [1, 2, 3]
}
###

# @name getOne
GET {{baseUrl}}/{{id}}

###

# @name update
PUT {{baseUrl}}/{{id}}

{
  "name": "potato-{{$guid}}"
}
###

# @name update
PUT {{baseUrl}}/{{id}}

{
  "name": "potato-{{$guid}}",
  "movies": [4]
}
###

# @name remove
DELETE {{baseUrl}}/{{id}}

###
