@baseUrl=http://localhost:8080/genres
@id={{create.response.body.id}}

# @name getAll
GET {{baseUrl}}

###

# @name create
POST {{baseUrl}}
Content-Type: application/json

{
  "name": "jose-{{$guid}}"
}
###

# @name getOne
GET {{baseUrl}}/{{id}}

###

# @name update
PUT {{baseUrl}}/{{id}}

{
  "name": "potato-{{$guid}}"
}
###

# @name update
PUT {{baseUrl}}/{{id}}

{
  "name": "potato-{{$guid}}",
  "movies": [
    { "movie_id": 4 }
  ]
}
###

# @name remove
DELETE {{baseUrl}}/{{id}}

###
